name: trade-ai
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ta-lib
  - numpy=1.26.4
  - pandas
  - yfinance
  - scikit-learn
  - matplotlib
  - scipy
  - pip
  - pip:
    - streamlit
    - tensorflow
