name: trade-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # ここでTA-Libをバイナリとしてインストールします
  - python=3.10
  - ta-lib
  - numpy<2.0.0
  - pandas
  - yfinance
  - scikit-learn
  - matplotlib
  - scipy
  - pip
  - pip:
    - streamlit
    - tensorflow
